//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incomes
    {
        public int IncomeID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int RoomNo { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
